### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by linux-leo** [SadWeeble/Kromer-CYF#1]
I saw your post on reddit and expected some mod ports or examples, but the last commit is from 4 months.
Its totally fine if you're busy, just want to know if this project is still developed

**Comment by SadWeeble** [comment]
Other CYK competitors have been cropping up, and from what I've seen they seem better than Kromer. I might return to this, but I've got so many other things going on, I'd rather let the real professionals do their job.

**Comment by linux-leo** [comment]
Thanks for your comment. I found the kristal engine as an alternative to cyk and will use that for my project.
